### ISSUE TITLE
When I click "Settings..." it crashes.

### ISSUE THREAD

**Issue by almo2001** [danielchalmers/DesktopClock#1]
This is on Windows 11, and I bought it on the Windows store.

**Comment by danielchalmers** [comment]
Could you send me the link where you downloaded it from? @almo2001

**Comment by almo2001** [comment]
https://www.microsoft.com/store/productId/9NJM62PGW2MN

**Comment by danielchalmers** [comment]
Hi, that is a fraudulent app, not uploaded by me. You should report it to Microsoft and contact them for a refund @almo2001

**Comment by almo2001** [comment]
Ok! Thanks for the info. I will do that. :)
