### ISSUE TITLE
always crashed while clicking "Settings..."

### ISSUE THREAD

**Issue by twinus** [danielchalmers/DesktopClock#12]
1. As title.
2. I have to re-do all the settings about font size, color, location... etc each time I restart my computer.
3. My OS: Windows11 64bit HomeEdtition.

So, please help to fix it asap. thank you.

**Comment by danielchalmers** [comment]
Where did you get the app from? Windows Store?

**Comment by twinus** [comment]
I bought it from Windows Store (in TW) on Double 10th Day Last Year.
Ordered #: 7697083208.
(If you need the purchased proof, I can send it by Email.)

So, would you like to fix it now?

**Comment by danielchalmers** [comment]
That's not an official app. I didn't make it and won't be fixing it so you should contact Microsoft for a refund.

https://github.com/danielchalmers/DesktopClock/issues/1#issuecomment-1289776486

**Comment by danielchalmers** [comment]
and I suggest sending Microsoft this issue when you ask for a refund so they know what's going on

**Comment by twinus** [comment]
Feel sorry to hear that.
No comment about fixing it or not.

But I just don’t get it why it’s not an official app which I bought it from Win Store.
As a customer, I think I don’t need to know or check out if it is an official app whoever uploaded before I buy it.
What I think simply is: I payed for it, then I have rights to ask for a fix, that’s all.

As you said so, “they know what’s going on”, but I don’t know what’s going on.
It’s not a problem to ask MS to refund, it’s not a bunch of money after all. But, indeed, this makes me feel that Windows Store is not trustworthy at all.

And, furthermore, if this app is yours, you didn’t upload it, why I still can see it now in Win Store. Since you’re not going to do anything about it, then please don’t ignore such a case. You might have to contact MS instead of we customers.

PS. No offense if I used any improper words above, ‘cos English is not my mother language. If there’s any expression makes you feel uncomfortable, I say sorry.
