### ISSUE TITLE
Special Format as in The Linked Image

### ISSUE THREAD

**Issue by DestoGit** [danielchalmers/DesktopClock#13]
Any way to customize the clock like this one?

3:18 PM
2 March
   Thursday

[Special Clock](https://i.ibb.co/61GxfL3/chrome-Az-Xzot-MW6-Y.png)

**Comment by danielchalmers** [comment]
not at the moment unfortunately

suggested at #5

**Comment by DestoGit** [comment]
Just found some WxPython similar project here if it can help update this one:

https://web.archive.org/web/20230401165114/https://wiki.wxpython.org/How%20to%20create%20a%20customized%20frame%20-%20Part%206%20%28Phoenix%29

Source code scripts zip:

https://wiki.wxpython.org/How%20to%20create%20a%20customized%20frame%20-%20Part%206%20%28Phoenix%29?action=AttachFile&do=get&target=source.zip

Thanks for next update!
