### ISSUE TITLE
Totally Lost Noobie Here

### ISSUE THREAD

**Issue by TerryZeszut** [danielchalmers/DesktopClock#15]
So I'd like to put this clock on my desktop. However, I have no idea how to do this. I do have an account with GitHub but have no idea how to proceed. Can anyone guide me to a tutorial or explain how this is done?

Thanks in advance.

**Comment by KunjanChauhan** [comment]
On the main page (https://github.com/danielchalmers/DesktopClock), look at the right side and you will see a section titled Releases.

**Comment by TerryZeszut** [comment]
Thanks Kunjan. The EXE stalled on the install but the MSI worked perfectly :)

**Comment by boxerpost** [comment]
I want to offer an automatic change of style based on what wallpaper is on the desktop. I have an automatic wallpaper change from bing for every day. And it would be great if your program could change the style automatically when the wallpaper changed. Maybe my idea will be useful. Thank you!
