### ISSUE TITLE
Show/Hide Desktop

### ISSUE THREAD

**Issue by dseplars** [danielchalmers/DesktopClock#16]
The command for hide desktop (Win + D) hides the clock. 

Sometimes showing after hiding doesn't show all apps if it's been a while, so the clock completely disappears.

**Comment by danielchalmers** [comment]
Thanks for the report. Windows has always been weird regarding the always-on-top setting, not sure what the right solution is right now unfortunately.

**Comment by danielchalmers** [comment]
Also inconsistent between versions of Windows https://stackoverflow.com/questions/10009623/keeping-window-visible-through-show-desktop-wind
