### ISSUE TITLE
New format - just the time, no pm or am

### ISSUE THREAD

**Issue by teach1st** [danielchalmers/DesktopClock#18]
I'm good at knowing if the time is PM or AM. How about a time-only format (no date) that excludes the PM and AM, i.e 10:26? The extra characters get in the way of my positioning the clock advantageously. Please let me know if there's a way to do this with advanced settings.

**Comment by danielchalmers** [comment]
There's an option in advanced settings to control the format. This format is specified in:

- https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings
- https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

**Comment by teach1st** [comment]
Thanks, Daniel! "h:mm" worked like a charm.
