### ISSUE TITLE
Setting Requests

### ISSUE THREAD

**Issue by TheWolfBunny64** [danielchalmers/DesktopClock#21]
Here are some settings I highly recommend adding in a future version of DesktopClock. While I really appreciate how it works, I really can't help but think there are some features that are missing for the DesktopClock, in order to be my new go-to portable clock app on Windows 11. Two of them to be more specific. So listen closely, and take notes, Daniel!

- Disable Dragging (This way, the clock stays in the position even when you click on it. However, its right-click menu should still be accessible when Disable Dragging is enabled at anytime.)

- Text Alignment Settings (Left, Center, and Right). This setting is pretty important. Because, let's say I want to display the current time in the right text alignment without a leading 0 sometimes (i.e., H:nn). This way, the numbers don't move when, say for example, the clock hits 10:00 AM, or 10:00 in 24-hr. format.

**Comment by danielchalmers** [comment]
Thank you for the suggestions!

Drag to move is optional as of 54168742e8ecc28f3bd67e8ee453eb84df0fa70d in [v3.1.0-beta1](https://github.com/danielchalmers/DesktopClock/releases/tag/v3.1.0-beta1)

For the text alignment I think it could go two ways:

- Simpler to implement:
  - Let user define a static width and an alignment as mentioned
  - Works with basic WPF concepts
  - User will have to change the width themselves if they change the format, but it does let them freely control padding
- Less simple:
  - Grow the window from a docked point; Left or Right
  - WPF natively grows rightward, but making it grow to the left is still possible with something like https://stackoverflow.com/questions/3607204/wpf-expand-window-to-the-left
  - User would be able to dock the clock in the right corner of a monitor without it spilling over when the width changes
