### ISSUE TITLE
Multimonitor issue

### ISSUE THREAD

**Issue by Kubino77** [danielchalmers/DesktopClock#23]
Hello,
A great tool, sir!
I have a small problem with my 3 monitor configuration. When DesktopClock starts automatically, it starts 3x, and I have to close the two extra clocks manually. So if you could fix this problem in your next update, that would be great. I would also appreciate the right alignment option in the menu (or docking to the side without overflowing).
thank you.

**Comment by danielchalmers** [comment]
Thanks, I'm glad you're liking it!

- Do the 3 clocks all start in the same place on top of each other? 
- Are you using v3.0.0 or v3.1.0-beta1?
- Could you go to `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` in RegEdit and tell me how many have their data as the same DesktopClock exe? Expecting 3.

I'll look more into it, but in the meantime you should be able to uncheck "Start with PC" on two of them OR go into Task Manager and disable two under the Startup tab.

Thank you!

**Comment by Kubino77** [comment]
Turned out, it was my mistake... I had run several DC instances (they showed only one taskbar icon). Nor stable nor beta exhibits this issue now :) Sorry for making a fuss.

**Comment by danielchalmers** [comment]
> Turned out, it was my mistake... I had run several DC instances (they showed only one taskbar icon). Nor stable nor beta exhibits this issue now :) Sorry for making a fuss.

No problem at all, glad it's solved!
