### ISSUE TITLE
downoad Desktopclock

### ISSUE THREAD

**Issue by Tafrick-333** [danielchalmers/DesktopClock#28]
How can I download Desktopclock? There is no visible download button. And I am not even very old.

**Comment by danielchalmers** [comment]
it's under Assets on the download page

![image](https://github.com/danielchalmers/DesktopClock/assets/7112040/642bc5fa-06a0-42da-ada4-d8546bb4788e)

https://github.com/danielchalmers/DesktopClock/releases
