### ISSUE TITLE
suggestion: add theme like windows cursor

### ISSUE THREAD

**Issue by u-Sir** [danielchalmers/DesktopClock#3]
like this 
![图片](https://user-images.githubusercontent.com/93647031/209070060-a6b4ebd1-6fbb-4ff7-832d-3139d6355026.png)

**Comment by u-Sir** [comment]
another suggestion: add option to auto hide when full-screen

**Comment by danielchalmers** [comment]
Are you looking for a theme that inverts in some way? Or a gradient?

**Comment by u-Sir** [comment]
> Are you looking for a theme that inverts in some way? Or a gradient?

yeah,inverts
