### ISSUE TITLE
Request: New Time Format

### ISSUE THREAD

**Issue by dlbeeson** [danielchalmers/DesktopClock#30]
Love your DesktopClock.
The format I find most useful is Monday, November 27, 09:18 HOWEVER the military time (24 hour time confuses me.)  

Could you PLEASE add a Format just like that one, but with AM/PM time?

Monday, November 27,  05:30 PM.

Thank you very much for considering this request.

**Comment by danielchalmers** [comment]
Right now you can change Format to `dddd, MMMM dd, hh:mm tt` in Advanced settings, but in the next few weeks I'll release an update that adds 12-hour formats to the right click menu due to your suggestion 🙂

**Comment by dlbeeson** [comment]
Daniel,Thank you so very much!  I have no User Guide or any Help to know how to modify the Advanced Settings, but your email solved it.  Thank you very much!Dan

---------- Original Message ----------
Return-Path: ***@***.***>
Received: from mx04.dca.untd.com (mx04.dca.untd.com [10.171.44.34])
 by maildeliver04.vgs.untd.com with SMTP id AABUYLLSPABWKTY2
 for ***@***.***> (sender ***@***.***>);
 Mon, 27 Nov 2023 15:45:17 -0800 (PST)
Authentication-Results: mx04.dca.untd.com; DKIM=PASS
Received-SPF: None
Received: from out-23.smtp.github.com (out-23.smtp.github.com [192.30.252.206])
 by mx04.dca.untd.com with SMTP id AABUYLLSNAHWZSN2
 for ***@***.***> (sender ***@***.***>);
 Mon, 27 Nov 2023 15:45:16 -0800 (PST)
Received: from github.com (hubbernetes-node-dc2584e.ac4-iad.github.net [10.52.136.16])
 by smtp.github.com (Postfix) with ESMTPA id 857945E0A6F
 for ***@***.***>; Mon, 27 Nov 2023 15:45:15 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
 s=pf2023; t=1701128715;
 bh=Ttsd7lsiTChZUbf4it7KEqUcfn6EW7RAxz4LiS4Vr4U=;
 h=Date:From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
 List-Archive:List-Post:List-Unsubscribe:From;
 b=Tx/Gdq5JtfDBUDr/4ojdDd5hSzKpyZApH8RulKeQH+Rwudr33wtLzDTfhdi4R1Wav
 Rp0jJmtWUhHdp3VG80PiV0G9HTGbQMwm7Z5UEmGT6hv2/xnYwmFwbKbrdLP5aJvJ8N
 7bB1DuLM5adFrCFbOJHBeHWw+Hz9ea9JpPNcZJKU=
Date: Mon, 27 Nov 2023 15:45:15 -0800
From: Daniel Chalmers ***@***.***>
Reply-To: danielchalmers/DesktopClock ***@***.***>
To: danielchalmers/DesktopClock ***@***.***>
Cc: dlbeeson ***@***.***>, 
 Author ***@***.***>
Message-ID: ***@***.***>
In-Reply-To: ***@***.***>
References: ***@***.***>
Subject: Re: [danielchalmers/DesktopClock] Request: New Time Format (Issue
 #30)
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_65652a0b81e66_64d804806c4";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Precedence: list
X-GitHub-Sender: danielchalmers
X-GitHub-Recipient: dlbeeson
X-GitHub-Reason: author
List-ID: danielchalmers/DesktopClock <DesktopClock.danielchalmers.github.com>
List-Archive: https://github.com/danielchalmers/DesktopClock
List-Post: ***@***.***>
List-Unsubscribe: ***@***.***>,
 <https://github.com/notifications/unsubscribe/ABIOSWXLLOFTK2KA23RZQEDYGUQYXANCNFSM6AAAAAA74GTDUQ>
X-Auto-Response-Suppress: All
destinations: ***@***.***
X-GitHub-Recipient-Address: ***@***.***
X-UNTD-BPF: 06e13d39093d70b4247024241df939a450a5dd147084d194d5f4f984f4c544c5147db955cd6494e4fde4e485c9b98010800580fdc91491a0c4f460b9d46019150c041561490421b10d2db12530
X-UNTD-BodySize: 2638
X-UNTD-SPF: None
X-UNTD-DKIM: PASS
X-ContentStamp: 7:3:3431523787
X-MAIL-INFO:06e1093de1f991b5b01df9b0dd746921a90ced699921f5a9d08125b4f5308d3035303139b4911dfd54315070a5f9a43df9a509a47d60e5e06071d9c0e9bd71e949ddf4c48584c9f461c4e48525c95101e465c941fde590e0e0e9b47174714980492969e9e07479c0000004355099a45094d1a5d4d594d4442d4da939f5794d84a9e139557909a1e1c17931899991a4a4d4ad091d701dd0d0fd7475bd74154904f004490c042d0d113451c56455c97d00ad2919
X-UNTD-Peer-Info: ***@***.***
X-UNTD-UBE:-1


 
Right now you can change Format to dddd, MMMM dd, hh:mm tt in Advanced settings, but in the next few weeks I'll release an update that adds 12-hour formats to the right click menu due to your suggestion &#128578;
&mdash;
