### ISSUE TITLE
Clock is missing the last minute

### ISSUE THREAD

**Issue by MaluNoPeleke** [danielchalmers/DesktopClock#31]
I have tried DesktopClock 3.0.0 and 3.1.0 beta 2 but both versions show the same issue:
If I select the format "t" (09:00) it doesn't show the last minute:
![image](https://github.com/danielchalmers/DesktopClock/assets/1446541/1f050689-760a-44e8-b05f-0cb94516c053)
If I select the format "T" everything is displayed completly/correctly:
![image](https://github.com/danielchalmers/DesktopClock/assets/1446541/4725a3ea-6e1e-4653-bb9c-94ef00c53645)
How can I fix this?
This is the content of the settings file:

```
{
  "Format": "t",
  "CountdownFormat": "",
  "CountdownTo": "0001-01-01T00:00:00+00:00",
  "TimeZone": "",
  "FontFamily": "Consolas",
  "TextColor": "#FF212121",
  "OuterColor": "#FFF5F5F5",
  "BackgroundEnabled": false,
  "BackgroundOpacity": 0.9,
  "OutlineThickness": 0.2,
  "CornerRadius": 1.0,
  "Topmost": true,
  "ShowInTaskbar": false,
  "Height": 40,
  "RunOnStartup": true,
  "DragToMove": true,
  "RightAligned": false,
  "Placement": {
    "Length": 44,
    "Flags": 0,
    "ShowCommand": 1,
    "MinimizedPosition": {
      "X": -1,
      "Y": -1
    },
    "MaximizedPosition": {
      "X": -1,
      "Y": -1
    },
    "NormalBounds": {
      "Left": 1687,
      "Top": 5,
      "Right": 1800,
      "Bottom": 55
    }
  }
}
```

**Comment by danielchalmers** [comment]
I remember that being a problem in early versions of Windows 11. What version of Windows are you running in `winver`?

**Comment by MaluNoPeleke** [comment]
22H2:
![image](https://github.com/danielchalmers/DesktopClock/assets/1446541/a7dc1cf0-2129-4d98-b29b-740e6692c705)

**Comment by danielchalmers** [comment]
Thanks. I'm not able to reproduce it myself but I'll keep an eye on the issue.

**Comment by MaluNoPeleke** [comment]
I had the issue again with another system:

> Edition	Windows 11 Enterprise
> Version	22H2
> Betriebssystembuild	22621.2861
> Leistung	Windows Feature Experience Pack 1000.22681.1000.0

It happened when I switched external monitors (DesktopClock is placed on an external monitor in my case).
I guess if the monitor/pixel position is not available on start the clock is moved to another monitor/display (with another size/resolution in my case) and then cut off.

**Comment by mbx96** [comment]
No second figure when background disabled.
Off:

<img width="351" alt="Screenshot 2024-02-14 090128" src="https://github.com/danielchalmers/DesktopClock/assets/129048800/bb33b0cb-1490-456a-b097-35c1cace5c26">

switch

<img width="158" alt="Screenshot 2024-02-14 090206" src="https://github.com/danielchalmers/DesktopClock/assets/129048800/e3be078a-c373-47ce-8fd4-97c269b5e7dc">

On:

<img width="358" alt="Screenshot 2024-02-14 090151" src="https://github.com/danielchalmers/DesktopClock/assets/129048800/5fff29da-5463-4782-91cf-04fee1a9b628">

My System

<img width="268" alt="Screenshot 2024-02-14 090247" src="https://github.com/danielchalmers/DesktopClock/assets/129048800/8fccb3c1-cc80-47a8-8478-bf174461c034">

Thx for your work!
MBX

**Comment by MaluNoPeleke** [comment]
I just had the same issue happening again after a restart (before the restart it worked with two figures) but toggling on/off the background makes no difference.

**Comment by mbx96** [comment]
As workaround you can use Advanced settings:
```
  "BackgroundEnabled": true,
  "BackgroundOpacity": 0.01,
``` 
![image](https://github.com/danielchalmers/DesktopClock/assets/129048800/b95f5e32-446a-4381-96e6-28a116e6ed85)
