### ISSUE TITLE
Pre-release without signed author

### ISSUE THREAD

**Issue by MaluNoPeleke** [danielchalmers/DesktopClock#32]
I cannot install pre-release as they are not signed and I have no administrator privileges:
![image](https://github.com/danielchalmers/DesktopClock/assets/1446541/55aa9839-a97c-4782-aadf-d6e38c9ef28e)
Can you change this for future builds please?
Microsoft Store is blocked for me as well.

**Comment by danielchalmers** [comment]
I can't justify paying for the signing certificate. Does the portable exe have the same issue?

**Comment by breem42** [comment]
> From the three last builds only the installer of the 3.0.0 allows me to run. None of the portable exe files (not even for the stable 3.0.0) and both beta installers can be run on my system with my privileges.

Maybe you can use the latest ".msi" file.

Or if you really want to get involved, you can install [Visual Studio Community Edition](https://visualstudio.microsoft.com/vs/community/) then clone the git repository and compile it. I don't know how much you know about compiling and building programs, but for me it was a fun experiment that worked out.

**Comment by MaluNoPeleke** [comment]
Sadly no change with 4.0.0. I wonder why it works with stable 3.0.0 installer but no other version. I will stick to that version then.

**Comment by danielchalmers** [comment]
@MaluNoPeleke it could be that 3.0.0 has been out longer and has more downloads so it's more trusted? never fully looked into this stuff
