### ISSUE TITLE
How to install it on Windows 10

### ISSUE THREAD

**Issue by airsidworld** [danielchalmers/DesktopClock#34]
Hello,
Thanks for sharing this nice app. 
Could you please explain how to install it on Windows 10 please ?

**Comment by danielchalmers** [comment]
On the releases page and under Assets there will be an MSI installer

https://github.com/danielchalmers/DesktopClock/releases/tag/v4.0.0

![image](https://github.com/danielchalmers/DesktopClock/assets/7112040/7a1a03c9-a366-4ecb-9aff-5cd1a85ea557)

**Comment by airsidworld** [comment]
Thanks a lot. 
All my wishes for 2024.
