### ISSUE TITLE
Can you add sound?

### ISSUE THREAD

**Issue by PaulMohn** [danielchalmers/DesktopClock#38]
like DS Clock?
https://www.dualitysoft.com/dsclock/index.html

**Comment by danielchalmers** [comment]
what kind of sounds are you looking for?

**Comment by PaulMohn** [comment]
Custom/any sounds. Just the feature to prompt for picking a sound (wav or mp3).
Then make it trigger at custom intervals (the DS Cllock triggers every 15min, 30min an 1h).
Ideally a different sound per interval.

Thank you.

**Comment by danielchalmers** [comment]
Hi, I added basic sound options in [v4.1.0](https://github.com/danielchalmers/DesktopClock/releases/tag/v4.1.0). Just one interval and one sound for now. Please let me know what you think :)
