### ISSUE TITLE
Missing am/pm with some fonts?

### ISSUE THREAD

**Issue by timtucker-dte** [danielchalmers/DesktopClock#4]
Finding odd behavior (Windows 11, version 3.0 of DesktopClock).

I have date format set to:
M/d h:mm tt

If I select some fonts (like Calibri), the space where am/pm should appear has space allocated for display but is just blank.

If I select other fonts (like Consolas) or use "M/d h:mm t" to just show a single character for a/p, it appears as expected.

**Comment by danielchalmers** [comment]
I've only seen this on Windows 11 so far. Very strange.

**Comment by danielchalmers** [comment]
I haven't noticed this in a while. Is it possible that it was a Windows 11 issue that got fixed by Microsoft?

**Comment by timtucker-dte** [comment]
Testing again with the v3.1 beta and I'm not seeing the issue anymore either.

**Comment by timtucker-dte** [comment]
Testing again with the v3.1 beta and I'm not seeing the issue anymore either.
