### ISSUE TITLE
DesktopClock.exe V4.1.0 does not open in Windows 11 - File deemed as a threat

### ISSUE THREAD

**Issue by MAP6768** [danielchalmers/DesktopClock#40]
While I could not use or even download completely the file DesktopClock.exe (even when indicating that it was safe), I was able to successfully download the .msi file with Edge browser (not Chrome) after insisting that I keep it.
Something in those files triggers the threat protect mecanism.
Be that as it may, I was finally able to install DesktopClock with the .msi file.
However, the "Show background" feature does not work. The background is always there whether I toggle or not the Show Background. 
In the settings file, changing the "BackgroundEnabled": from true to false, does not change anything.
I had to put the "BackgroundOpacity": to 0.0,  
Thank you for your kind assistance.

**Comment by MAP6768** [comment]
Thanks Daniel,

The Show Background works.

By the way, for the sound notification, how do you program the interval?

 

On your web page you show: "WavFileInterval": "00:01:00",

Does it ring every minute or every hour?

Cheers,

 

Michel

**Comment by danielchalmers** [comment]
It's `hh:mm:ss` so once a minute :)

**Comment by MAP6768** [comment]
Great it works 😊
