### ISSUE TITLE
MINIMIZE THE APP IN SYSTEM TRAY

### ISSUE THREAD

**Issue by Smk04** [danielchalmers/DesktopClock#41]
Would love it if it can minimize to system tray. No issues man. I love it
![Screenshot 2024-01-13 010054](https://github.com/danielchalmers/DesktopClock/assets/85932180/c2a87749-e5be-403f-b41c-424684fb6b3e)

**Comment by sherozsamatov** [comment]
Minimize the app to system tray so it doesn't show as running app. In other words, add 'Hide from Alt+Tab'

**Comment by sherozsamatov** [comment]
Would be good to minimize it to tray.

![image](https://github.com/danielchalmers/DesktopClock/assets/50622092/c3a4d92c-d0af-403d-9afc-08401aa1f983)

**Comment by sherozsamatov** [comment]
Hi Any update?
I love the widget! Any chance to implement this feature???
Would really love to see it minimize to tray. Thanks!

**Comment by tdnzr** [comment]
I don't know when this feature was implemented, but you can definitely minimize the app to tray. Just right-click the clock and unselect "Show icon in taskbar".

**Comment by danielchalmers** [comment]
@sherozsamatov 

tdnzr is right - you should be able to disable `Show icon in taskbar` and then choose `Hide for now` to get the desired result.
