### ISSUE TITLE
Support for multi-line date format

### ISSUE THREAD

**Issue by timtucker-dte** [danielchalmers/DesktopClock#5]
Would it be possible to support multi-line dates?

If I try putting a newline character in a date it just cuts off the second line.

I'd like to have a taller display that includes the day of the month and the time on separate lines.

**Comment by danielchalmers** [comment]
It uses [.NET datetime string formats](https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings) and I can't find any way of including newlines with that. I'll keep this in mind though if I decide to rework it because it's a good idea.

**Comment by f4x4** [comment]
> It uses [.NET datetime string formats](https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings) and I can't find any way of including newlines with that. I'll keep this in mind though if I decide to rework it because it's a good idea.

Ok, thank you. It would be appreciated!

**Comment by danielchalmers** [comment]
A special formatter is in place to be able to handle newline characters after c6d45d089e877815190be6057362ba45c8381502 but the outlined textblock can't handle them at the moment. I'm not good at graphics stuff so I'm not sure how to get that working but I got it from https://stackoverflow.com/a/35262509 if anyone has any ideas.
