### ISSUE TITLE
Are OTF fonts supported?

### ISSUE THREAD

**Issue by sidola** [danielchalmers/DesktopClock#54]
Hi, I'm trying to change the font to an OTF font but it seems to be quietly failing. Is there a limitation on what font formats are allowed? All of my TTF fonts work fine.

**Comment by danielchalmers** [comment]
Which font are you trying to use?

**Comment by sidola** [comment]
https://www.dafont.com/akira-expanded.font

Using the config value `"FontFamily": "AkiraExpanded-SuperBold"`

**Comment by danielchalmers** [comment]
Try "Akria Expanded" or "Akria Super". Fonts will be in a UI picker in v5 to make it easier to find them

**Comment by sidola** [comment]
Huh, yeah "Akira Super" works, as well as "Akira Super Bold", meanwhile "Akira Expanded" doesn't work. Interesting. Thanks for the help!
