### ISSUE TITLE
Free text to distinguish different clocks?

### ISSUE THREAD

**Issue by deignanfr** [danielchalmers/DesktopClock#59]
Hi,
Thank's for developping this tool.
My main use case is that I have a wide screen and the windows clock is "all the way over there". I wanted a clock near a natural position for my focus.
Then of course I see that I can have several clocks in different timezones. EST! Brazil! India! ... And Confused!

I would like to have (either or both) the possibility of putting a free text before or after the clock display, and/or to automatically have the name of the timezone added after the clock display.

Thanks,
Ciaran

**Comment by danielchalmers** [comment]
Hi, are you thinking something like this format below?

![image](https://github.com/user-attachments/assets/338b93f3-3501-440f-8fb5-77b39744ace9)

![image](https://github.com/user-attachments/assets/f8ebf3f4-3156-4dd1-8ba9-8d2c9cfb3d87)
