### ISSUE TITLE
Alt+tab showing windows even with -show taskbar icon- disabled. 

### ISSUE THREAD

**Issue by lashermayfair** [danielchalmers/DesktopClock#6]
I have this issue, I use this clock on two displays, it always shows in alt tab, windows+tab. Is there a way to implement a way to stop showing in the alt+tab?

**Behavior:** 
window showing on alt+tab

**expected behavior:**
window hidden on alt+tab

**thanks.**

**Comment by danielchalmers** [comment]
https://github.com/dotnet/wpf/issues/3623
