### ISSUE TITLE
Formatting to include the time and or custom text..

### ISSUE THREAD

**Issue by Masheen88** [danielchalmers/DesktopClock#8]
It would be nice to have the ability to see the time and selected time zone, especially with multiple clocks. Perhaps an even easier solution would be to include the ability to input custom text. I did try to poke around the advanced settings file but it would not allow for additional text. Thanks so much for this awesome app. A real time saver! ;)

example: **someTextHere** Sunday, Jan 29, 10:05:02

**Comment by Masheen88** [comment]
I was able to code in this feature. Below is a screenshot of my working version. I'm happy to share the add code if anyone is interested.

![image](https://user-images.githubusercontent.com/9340950/229728266-515e4464-e26c-4cbc-8ed3-b78b4a031d54.png)

**Comment by danielchalmers** [comment]
Hi @Masheen88, I'm not sure when I'll be working on this app again, but I like the suggestion and greatly appreciate you sharing your solution to it.

Any chance you could take a shot at submitting your changes as a pull request? I think it would essentially look like:
- Delete the Masheen88/DesktopClock repository (to avoid naming conflict with next step)
- Fork this repository https://github.com/danielchalmers/DesktopClock/fork
- `git clone https://github.com/Masheen88/DesktopClock`, write over it with your updated code, then commit and push
- Finally create a new pull request with that new commit https://github.com/danielchalmers/DesktopClock/pulls

Let me know if you have any issues with those steps, I'm writing them from memory. Thanks again!
